apiVersion: apps/v1
kind: Deployment
metadata:
    name: madome-user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: madome-user
    template:
        metadata:
            labels:
                app: madome-user
        spec:
            containers:
                - name: madome-user
                  image: madome-user:{VERSION}
                  imagePullPolicy: Never
                  resources:
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 3112
                        protocol: TCP
                  volumeMounts:
                      - mountPath: /.env
                        name: env-volume
                        readOnly: true
            volumes:
                - name: env-volume
                  hostPath:
                      path: "{WORK_DIR}/.env.release"
---
apiVersion: v1
kind: Service
metadata:
    name: madome-user
spec:
    # 모든 서버를 쿠버네티스로 배포하게 된다면, ClusterIp로 바꾸고 Ingress 사용함
    type: NodePort
    selector:
        app: madome-user
    ports:
        - port: 3112
          protocol: TCP
          nodePort: 32766
---
apiVersion: v1
kind: Endpoints
metadata:
    name: postgres-user
subsets:
    - addresses:
          - ip: "{POSTGRES_HOST}"
      ports:
          - port: 5432
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-user
spec:
    ports:
        - port: 5432
          targetPort: 5432
