apiVersion: v1
kind: Service
metadata:
    name: madome-user
spec:
    type: NodePort
    selector:
        app: madome-user
    ports:
        - port: 3112
          protocol: TCP
          nodePort: 32766
